(define-module (canary input)
  #:use-module (canary protocol)
  #:use-module (ice-9 textual-ports)
  #:export (read-key-msg
            enable-input-logging
            disable-input-logging))

(define *input-log-enabled* #f)
(define *input-log-file* "/tmp/guile-canary-input-debug.log")

(define (enable-input-logging . args)
  (when (pair? args)
    (set! *input-log-file* (car args)))
  (set! *input-log-enabled* #t)
  (let ((port (open-file *input-log-file* "a")))
    (display "=== Input logging enabled ===\n" port)
    (close-port port))
  #t)

(define (disable-input-logging)
  (set! *input-log-enabled* #f)
  #t)

(define (%ilog fmt . args)
  (when *input-log-enabled*
    (let ((port (open-file *input-log-file* "a")))
      (apply format port fmt args)
      (newline port)
      (close-port port))))

(define (read-key-msg)
  (let ((port (current-input-port)))
    (if (char-ready? port)
        (let ((char (read-char port)))
          (when char
            (%ilog "read-key-msg: char='~a' code=~d" char (char->integer char))
            (cond
             ((char=? char #\escape)
              (%ilog "read-key-msg: ESC detected -> parse-escape-start")
              (parse-escape-start port))
             ((= (char->integer char) 127)
              (%ilog "read-key-msg: DEL(127) -> :backspace")
              (key 'backspace))
             ((< (char->integer char) 32)
              (let ((k (ctrl-char-to-key char)))
                (%ilog "read-key-msg: control char ~d -> ~a" (char->integer char) k)
                (key k '(control))))
             (else
              (%ilog "read-key-msg: graphic '~a'" char)
              (key char)))))
        #f)))

(define (ctrl-char-to-key char)
  (let ((code (char->integer char)))
    (case code
      ((8)  'backspace)
      ((9)  'tab)
      ((10) 'enter)
      ((13) 'enter)
      (else (integer->char (+ code 96))))))

(define (parse-escape-start port)
  (let loop ((tries 0))
    (cond
     ((and (not (char-ready? port)) (< tries 8))
      (usleep 5000)
      (loop (+ tries 1)))
     (else
      (%ilog "parse-escape-start: waited ~d ticks, ready=~a" tries (char-ready? port))
      (if (char-ready? port)
          (let ((next (read-char port)))
            (%ilog "parse-escape-start: next='~a' code=~d" next (char->integer next))
            (if next
                (parse-escape-sequence next port)
                (key 'escape)))
          (begin
            (%ilog "parse-escape-start: lone ESC -> escape")
            (key 'escape)))))))

(define (parse-escape-sequence char port)
  (cond
   ((char=? char #\[)
    (%ilog "parse-escape-sequence: CSI '['")
    (parse-csi-sequence port))
   ((char=? char #\O)
    (%ilog "parse-escape-sequence: SS3 'O'")
    (parse-ss3-sequence port))
   ((char-alphabetic? char)
    (key char '(meta)))
   ((= (char->integer char) 127)
    (key 'backspace '(meta)))
   (else
    (%ilog "parse-escape-sequence: unknown ESC seq start '~a'" char)
    (key 'escape))))

(define (parse-csi-sequence port)
  (if (not (char-ready? port))
      (key 'unknown)
      (let ((ch (read-char port)))
        (%ilog "parse-csi-sequence: ch='~a' (code ~a)" ch (char->integer ch))
        (cond
         ((char=? ch #\<)
          (parse-mouse-sequence port))
         ((memv ch '(#\A #\B #\C #\D #\H #\F #\Z))
          (case ch
            ((#\A) (%ilog "parse-csi-sequence: -> up") (key 'up))
            ((#\B) (%ilog "parse-csi-sequence: -> down") (key 'down))
            ((#\C) (%ilog "parse-csi-sequence: -> right") (key 'right))
            ((#\D) (%ilog "parse-csi-sequence: -> left") (key 'left))
            ((#\H) (%ilog "parse-csi-sequence: -> home") (key 'home))
            ((#\F) (%ilog "parse-csi-sequence: -> end") (key 'end))
            ((#\Z) (%ilog "parse-csi-sequence: -> backtab") (key 'backtab))))
         ((char-numeric? ch)
          (let loop ((digits (list ch))
                     (term #f))
            (if (and (not term)
                     (char-ready? port)
                     (let ((c (peek-char port)))
                       (or (char-numeric? c) (char=? c #\~) (char=? c #\;))))
                (let ((c (read-char port)))
                  (if (or (char=? c #\~) (char=? c #\;))
                      (loop digits c)
                      (loop (append digits (list c)) term)))
                (begin
                  (%ilog "parse-csi-sequence: digits='~a' term='~a'"
                         (list->string digits) term)
                  (if (and term (char=? term #\~))
                      (let ((num (string->number (list->string digits))))
                        (case num
                          ((3) (%ilog "parse-csi-sequence: -> delete")
                               (key 'delete))
                          ((200) (%ilog "parse-csi-sequence: bracketed paste start")
                                 (parse-bracketed-paste port))
                          (else (key 'unknown))))
                      (key 'unknown))))))
         (else
          (let loop ()
            (when (char-ready? port)
              (read-char port)
              (loop)))
          (key 'unknown))))))

(define (parse-ss3-sequence port)
  (if (not (char-ready? port))
      (key 'unknown)
      (let ((ch (read-char port)))
        (%ilog "parse-ss3-sequence: ch='~a'" ch)
        (case ch
          ((#\A) (key 'up))
          ((#\B) (key 'down))
          ((#\C) (key 'right))
          ((#\D) (key 'left))
          ((#\H) (key 'home))
          ((#\F) (key 'end))
          (else  (key 'unknown))))))

(define (parse-mouse-sequence port)
  (let ((params '())
        (term #f))
    (let loop ()
      (when (and (not term) (char-ready? port))
        (let ((ch (peek-char port)))
          (cond
           ((or (char=? ch #\M) (char=? ch #\m))
            (set! term (read-char port)))
           ((char=? ch #\;)
            (read-char port)
            (loop))
           ((char-numeric? ch)
            (let read-num ((digits '()))
              (if (and (char-ready? port) (char-numeric? (peek-char port)))
                  (read-num (cons (read-char port) digits))
                  (begin
                    (set! params (cons (string->number (list->string (reverse digits))) params))
                    (loop)))))
           (else
            (read-char port)
            (loop))))))
    (if (and term (= (length params) 3))
        (let ((button (list-ref params 2))
              (x      (list-ref params 1))
              (y      (list-ref params 0))
              (action (if (char=? term #\M) 'press 'release)))
          (%ilog "parse-mouse-sequence: btn=~a x=~a y=~a action=~a" button x y action)
          (cond
           ((= button 64) (mouse x y 64 'scroll-up))
           ((= button 65) (mouse x y 65 'scroll-down))
           (else          (mouse x y button action))))
        (key 'unknown))))

(define (parse-bracketed-paste port)
  (%ilog "parse-bracketed-paste: reading pasted text")
  (let ((text ""))
    (let loop ()
      (when (char-ready? port)
        (let ((ch (read-char port)))
          (cond
           ((char=? ch #\escape)
            (if (and (char-ready? port)
                    (char=? (peek-char port) #\[))
                (begin
                  (read-char port)
                  (if (and (char-ready? port)
                          (char=? (peek-char port) #\2))
                      (begin
                        (read-char port)
                        (read-char port)
                        (read-char port)
                        (read-char port)
                        (%ilog "parse-bracketed-paste: end marker found")
                        #f)
                      (begin
                        (set! text (string-append text (string #\escape #\[)))
                        (loop))))
                (begin
                  (set! text (string-append text (string #\escape)))
                  (loop))))
           (else
            (set! text (string-append text (string ch)))
            (loop))))))
    (%ilog "parse-bracketed-paste: got ~d chars" (string-length text))
    (key 'paste)))
