(define-module (canary markdown)
  #:use-module (canary view)
  #:use-module (canary layout)
  #:use-module (srfi srfi-1)
  #:export (markdown-view))

(define (header-level s)
  (let ((n (string-length s)))
    (let loop ((i 0))
      (cond
       ((>= i n) 0)
       ((char=? (string-ref s i) #\#) (loop (+ i 1)))
       (else i)))))

(define (line->node line)
  (let ((trimmed (string-trim-both line)))
    (cond
     ((string-null? trimmed)
      (txt ""))
     ((and (> (string-length trimmed) 2)
           (string=? (substring trimmed 0 3) "```"))
      #f)
     ((char=? (string-ref trimmed 0) #\#)
      (let* ((level (header-level trimmed))
             (content (string-trim-both (substring trimmed level)))
             (prefix (make-string level #\#)))
        (txt (string-append prefix " " content)
             #:fg (case level
                      ((1) 'heading)
                      ((2) 'accent)
                      (else 'info))
             #:bold)))
     ((and (char=? (string-ref trimmed 0) #\>) (> (string-length trimmed) 1))
      (txt (string-append "│ " (string-trim-both (substring trimmed 1)))
           #:fg 'muted))
     ((and (> (string-length trimmed) 1)
           (char=? (string-ref trimmed 0) #\-)
           (char=? (string-ref trimmed 1) #\space))
      (txt (string-append "  • " (substring trimmed 2))))
     ((and (>= (string-length trimmed) 3) (string-every #\- trimmed))
      (txt (make-string 40 #\─) #:fg 'dim))
     (else
      (txt trimmed)))))

(define (markdown-view text)
  (let* ((lines (string-split text #\newline))
         (nodes (filter (lambda (x) x) (map line->node lines))))
    (apply vbox nodes)))
