(define-module (canary render)
  #:use-module (canary view)
  #:use-module (canary draw)
  #:use-module (canary borders)
  #:use-module (srfi srfi-1)
  #:export (render
            view->cmds))

(define (clamp s max-w)
  (let ((n (string-length s)))
    (cond
     ((<= max-w 0) "")
     ((<= n max-w) s)
     (else (substring s 0 max-w)))))

(define (render node cols rows)
  (view->cmds node (make-rect 0 0 cols rows)))

(define (view->cmds node rect)
  (cond
   ((rect-empty? rect) '())
   ((not node) '())
   ((string? node)
    (list (make-text (rect-col rect) (rect-row rect)
                     (clamp node (rect-w rect))
                     'default '())))
   ((text-node? node)
    (list (make-text (rect-col rect) (rect-row rect)
                     (clamp (text-node-str node) (rect-w rect))
                     (text-node-face node)
                     (text-node-attrs node))))
   ((fill-node? node)
    (let* ((w (min (fill-node-w node) (rect-w rect)))
           (h (min (fill-node-h node) (rect-h rect))))
      (list (make-fill (rect-col rect) (rect-row rect) w h
                       (fill-node-face node)))))
   ((spacer-node? node) '())
   ((cursor-node? node)
    (list (make-cursor (+ (rect-col rect) (cursor-node-col node))
                       (+ (rect-row rect) (cursor-node-row node))
                       (cursor-node-style node))))
   ((vbox-node? node)
    (render-vbox node rect))
   ((hbox-node? node)
    (render-hbox node rect))
   ((boxed-node? node)
    (render-boxed node rect))
   ((pad-node? node)
    (render-pad node rect))
   ((align-node? node)
    (render-align node rect))
   ((width-node? node)
    (render-width node rect))
   ((height-node? node)
    (render-height node rect))
   ((overlay-node? node)
    (append (view->cmds (overlay-node-base node) rect)
            (append-map
             (lambda (p)
               (let* ((col   (placement-col p))
                      (row   (placement-row p))
                      (child (placement-child p))
                      (s (view-size child))
                      (cw (min (car s) (- (rect-w rect)
                                          (- col (rect-col rect)))))
                      (ch (min (cdr s) (- (rect-h rect)
                                          (- row (rect-row rect))))))
                 (view->cmds child (make-rect col row cw ch))))
             (overlay-node-overlays node))))
   ((static-node? node)
    (let ((cached (static-node-cached-rect node)))
      (if (and cached (rect=? cached rect))
          (static-node-cached-cmds node)
          (let ((cmds (view->cmds (static-node-child node) rect)))
            (set-static-node-cached-rect! node rect)
            (set-static-node-cached-cmds! node cmds)
            cmds))))
   (else '())))

(define (bg-fill-cmds face rect)
  (if face
      (list (make-fill (rect-col rect) (rect-row rect)
                       (rect-w rect) (rect-h rect)
                       face))
      '()))

(define (render-vbox node rect)
  (let ((face (vbox-node-face node))
        (children (vbox-node-children node)))
    (append
     (bg-fill-cmds face rect)
     (let loop ((cs children) (row (rect-row rect)) (remaining (rect-h rect)) (acc '()))
       (cond
        ((or (null? cs) (<= remaining 0)) (reverse acc))
        (else
         (let* ((child (car cs))
                (s (view-size child))
                (cw (min (car s) (rect-w rect)))
                (ch (min (cdr s) remaining))
                (sub (make-rect (rect-col rect) row cw ch))
                (cmds (view->cmds child sub)))
           (loop (cdr cs) (+ row ch) (- remaining ch)
                 (append (reverse cmds) acc)))))))))

(define (render-hbox node rect)
  (let ((face (hbox-node-face node))
        (children (hbox-node-children node)))
    (append
     (bg-fill-cmds face rect)
     (let loop ((cs children) (col (rect-col rect)) (remaining (rect-w rect)) (acc '()))
       (cond
        ((or (null? cs) (<= remaining 0)) (reverse acc))
        (else
         (let* ((child (car cs))
                (s (view-size child))
                (cw (min (car s) remaining))
                (ch (min (cdr s) (rect-h rect)))
                (sub (make-rect col (rect-row rect) cw ch))
                (cmds (view->cmds child sub)))
           (loop (cdr cs) (+ col cw) (- remaining cw)
                 (append (reverse cmds) acc)))))))))

(define (render-boxed node rect)
  (cond
   ((or (< (rect-w rect) 2) (< (rect-h rect) 2)) '())
   (else
    (let* ((border (boxed-node-border node))
           (face (boxed-node-face node))
           (col (rect-col rect))
           (row (rect-row rect))
           (w (rect-w rect))
           (h (rect-h rect))
           (inner-w (- w 2))
           (inner-h (- h 2))
           (inner-rect (make-rect (+ col 1) (+ row 1) inner-w inner-h))
           (top-mid (make-string inner-w (string-ref (border-top border) 0)))
           (bot-mid (make-string inner-w (string-ref (border-bottom border) 0))))
      (append
       (bg-fill-cmds face rect)
       (list (make-text col row
                        (string-append (border-tl border) top-mid (border-tr border))
                        face '()))
       (let loop ((r (+ row 1)) (end (+ row h -1)) (acc '()))
         (cond
          ((>= r end) (reverse acc))
          (else
           (loop (+ r 1) end
                 (cons (make-text col r (border-left border) face '())
                       (cons (make-text (+ col w -1) r (border-right border) face '())
                             acc))))))
       (list (make-text col (+ row h -1)
                        (string-append (border-bl border) bot-mid (border-br border))
                        face '()))
       (view->cmds (boxed-node-child node) inner-rect))))))

(define (render-pad node rect)
  (let* ((t (pad-node-top node))
         (r (pad-node-right node))
         (b (pad-node-bottom node))
         (l (pad-node-left node))
         (inner (make-rect (+ (rect-col rect) l)
                           (+ (rect-row rect) t)
                           (max 0 (- (rect-w rect) l r))
                           (max 0 (- (rect-h rect) t b)))))
    (append (bg-fill-cmds (pad-node-face node) rect)
            (view->cmds (pad-node-child node) inner))))

(define (render-align node rect)
  (let* ((child (align-node-child node))
         (mode (align-node-mode node))
         (target-w (or (align-node-width node) (rect-w rect)))
         (s (view-size child))
         (cw (min (car s) target-w))
         (slack (max 0 (- target-w cw)))
         (offset (case mode
                   ((center) (quotient slack 2))
                   ((right) slack)
                   (else 0)))
         (sub (make-rect (+ (rect-col rect) offset)
                         (rect-row rect)
                         cw
                         (rect-h rect))))
    (view->cmds child sub)))

(define (render-width node rect)
  (let* ((target-w (min (width-node-w node) (rect-w rect)))
         (child (width-node-child node))
         (align (width-node-align node))
         (s (view-size child))
         (cw (min (car s) target-w))
         (slack (max 0 (- target-w cw)))
         (offset (case align
                   ((center) (quotient slack 2))
                   ((right) slack)
                   (else 0)))
         (sub (make-rect (+ (rect-col rect) offset)
                         (rect-row rect)
                         cw
                         (rect-h rect))))
    (view->cmds child sub)))

(define (render-height node rect)
  (let* ((target-h (min (height-node-h node) (rect-h rect)))
         (child (height-node-child node))
         (valign (height-node-valign node))
         (s (view-size child))
         (ch (min (cdr s) target-h))
         (slack (max 0 (- target-h ch)))
         (offset (case valign
                   ((center) (quotient slack 2))
                   ((bottom) slack)
                   (else 0)))
         (sub (make-rect (rect-col rect)
                         (+ (rect-row rect) offset)
                         (rect-w rect)
                         ch)))
    (view->cmds child sub)))
