(define-module (canary render)
  #:use-module (canary view)
  #:use-module (canary draw)
  #:use-module (canary borders)
  #:use-module (canary width)
  #:use-module (canary protocol)
  #:use-module (oop goops)
  #:use-module (srfi srfi-1)
  #:export (render
            view->cmds
            image-cmd->fallback-cmds))

(define (clamp s max-w) (string-display-clamp s max-w))

(define (rect-contains? rect x y)
  (and (<= (rect-col rect) x)
       (< x (+ (rect-col rect) (rect-w rect)))
       (<= (rect-row rect) y)
       (< y (+ (rect-row rect) (rect-h rect)))))

(define* (render node cols rows #:key (mouse-x -1) (mouse-y -1))
  (view->cmds node (make-rect 0 0 cols rows) mouse-x mouse-y))

(define (view->cmds node rect mx my)
  (cond
   ((rect-empty? rect) '())
   ((not node) '())
   ((string? node)
    (list (make-text (rect-col rect) (rect-row rect)
                     (clamp node (rect-w rect))
                     'default '())))
   ((text-node? node)
    (list (make-text (rect-col rect) (rect-row rect)
                     (clamp (text-node-str node) (rect-w rect))
                     (text-node-face node)
                     (text-node-attrs node))))
   ((text-runs-node? node)
    (render-text-runs node rect mx my))
   ((fill-node? node)
    (let* ((w (min (fill-node-w node) (rect-w rect)))
           (h (min (fill-node-h node) (rect-h rect))))
      (list (make-fill (rect-col rect) (rect-row rect) w h
                       (fill-node-face node)))))
   ((spacer-node? node) '())
   ((cursor-node? node)
    (list (make-cursor (+ (rect-col rect) (cursor-node-col node))
                       (+ (rect-row rect) (cursor-node-row node))
                       (cursor-node-style node))))
   ((vbox-node? node)    (render-vbox    node rect mx my))
   ((hbox-node? node)    (render-hbox    node rect mx my))
   ((boxed-node? node)   (render-boxed   node rect mx my))
   ((pad-node? node)     (render-pad     node rect mx my))
   ((margin-node? node)  (render-margin  node rect mx my))
   ((align-node? node)   (render-align   node rect mx my))
   ((width-node? node)   (render-width   node rect mx my))
   ((height-node? node)  (render-height  node rect mx my))
   ((overlay-node? node)
    (append (view->cmds (overlay-node-base node) rect mx my)
            (append-map
             (lambda (p)
               (let* ((col   (placement-col p))
                      (row   (placement-row p))
                      (child (placement-child p))
                      (s (view-size child))
                      (cw (min (car s) (- (rect-w rect)
                                          (- col (rect-col rect)))))
                      (ch (min (cdr s) (- (rect-h rect)
                                          (- row (rect-row rect))))))
                 (view->cmds child (make-rect col row cw ch) mx my)))
             (overlay-node-overlays node))))
   ((static-node? node)
    (let ((cached (static-node-cached-rect node)))
      (if (and cached (rect=? cached rect))
          (static-node-cached-cmds node)
          (let ((cmds (view->cmds (static-node-child node) rect mx my)))
            (set-static-node-cached-rect! node rect)
            (set-static-node-cached-cmds! node cmds)
            cmds))))
   ((image-node? node)
    (let* ((w (min (image-node-w node) (rect-w rect)))
           (h (min (image-node-h node) (rect-h rect))))
      (list (make-image (rect-col rect) (rect-row rect) w h
                        (image-node-px node) (image-node-py node)
                        (image-node-src-x node) (image-node-src-y node)
                        (image-node-src-w node) (image-node-src-h node)
                        (image-node-src node)
                        (image-node-fallback node)))))
   ((click-node? node)
    (let ((child-cmds (view->cmds (click-node-child node) rect mx my)))
      (append child-cmds
              (list (make-clickable (rect-col rect) (rect-row rect)
                                    (rect-w rect) (rect-h rect)
                                    (click-node-action node))))))
   ((hover-node? node)
    (let* ((child     (hover-node-child node))
           (hot?      (rect-contains? rect mx my))
           (effective (if hot? ((hover-node-styler node) child) child)))
      (view->cmds effective rect mx my)))
   ((is-a? node <object>)
    (view->cmds (memoized-view node (size (rect-w rect) (rect-h rect)))
                rect mx my))
   (else '())))

(define (image-cmd->fallback-cmds cmd)
  (view->cmds (image-fallback cmd)
              (make-rect (image-col cmd) (image-row cmd)
                         (image-w cmd) (image-h cmd))
              -1 -1))

(define (bg-fill-cmds face rect)
  (if face
      (list (make-fill (rect-col rect) (rect-row rect)
                       (rect-w rect) (rect-h rect)
                       face))
      '()))

(define (render-vbox node rect mx my)
  (let ((face (vbox-node-face node))
        (children (vbox-node-children node)))
    (append
     (bg-fill-cmds face rect)
     (let loop ((cs children) (row (rect-row rect)) (remaining (rect-h rect)) (acc '()))
       (cond
        ((or (null? cs) (<= remaining 0)) (reverse acc))
        (else
         (let* ((child (car cs))
                (s  (if (is-a? child <object>)
                        (view-size (memoized-view child (size (rect-w rect) remaining)))
                        (view-size child)))
                (cw (min (car s) (rect-w rect)))
                (ch (min (cdr s) remaining))
                (sub (make-rect (rect-col rect) row cw ch))
                (cmds (view->cmds child sub mx my)))
           (loop (cdr cs) (+ row ch) (- remaining ch)
                 (append (reverse cmds) acc)))))))))

(define (render-hbox node rect mx my)
  (let ((face (hbox-node-face node))
        (children (hbox-node-children node)))
    (append
     (bg-fill-cmds face rect)
     (let loop ((cs children) (col (rect-col rect)) (remaining (rect-w rect)) (acc '()))
       (cond
        ((or (null? cs) (<= remaining 0)) (reverse acc))
        (else
         (let* ((child (car cs))
                (s  (if (is-a? child <object>)
                        (view-size (memoized-view child (size remaining (rect-h rect))))
                        (view-size child)))
                (cw (min (car s) remaining))
                (ch (min (cdr s) (rect-h rect)))
                (sub (make-rect col (rect-row rect) cw ch))
                (cmds (view->cmds child sub mx my)))
           (loop (cdr cs) (+ col cw) (- remaining cw)
                 (append (reverse cmds) acc)))))))))

(define (splice-title top-mid title)
  (cond
   ((not title) top-mid)
   ((not (string? title)) top-mid)
   (else
    (let* ((tag    (string-append " " title " "))
           (tag-w  (string-length tag))
           (mid-w  (string-length top-mid))
           (offset 2))
      (cond
       ((> (+ offset tag-w) mid-w) top-mid)
       (else
        (string-append (substring top-mid 0 offset)
                       tag
                       (substring top-mid (+ offset tag-w) mid-w))))))))

(define (render-boxed node rect mx my)
  (cond
   ((or (< (rect-w rect) 2) (< (rect-h rect) 2)) '())
   (else
    (let* ((border (boxed-node-border node))
           (face (boxed-node-face node))
           (title (boxed-node-title node))
           (col (rect-col rect))
           (row (rect-row rect))
           (w (rect-w rect))
           (h (rect-h rect))
           (inner-w (- w 2))
           (inner-h (- h 2))
           (inner-rect (make-rect (+ col 1) (+ row 1) inner-w inner-h))
           (top-mid (splice-title
                     (make-string inner-w (string-ref (border-top border) 0))
                     title))
           (bot-mid (make-string inner-w (string-ref (border-bottom border) 0))))
      (append
       (bg-fill-cmds face rect)
       (list (make-text col row
                        (string-append (border-tl border) top-mid (border-tr border))
                        face '()))
       (let loop ((r (+ row 1)) (end (+ row h -1)) (acc '()))
         (cond
          ((>= r end) (reverse acc))
          (else
           (loop (+ r 1) end
                 (cons (make-text col r (border-left border) face '())
                       (cons (make-text (+ col w -1) r (border-right border) face '())
                             acc))))))
       (list (make-text col (+ row h -1)
                        (string-append (border-bl border) bot-mid (border-br border))
                        face '()))
       (view->cmds (boxed-node-child node) inner-rect mx my))))))

(define (render-pad node rect mx my)
  (let* ((t (pad-node-top node))
         (r (pad-node-right node))
         (b (pad-node-bottom node))
         (l (pad-node-left node))
         (inner (make-rect (+ (rect-col rect) l)
                           (+ (rect-row rect) t)
                           (max 0 (- (rect-w rect) l r))
                           (max 0 (- (rect-h rect) t b)))))
    (append (bg-fill-cmds (pad-node-face node) rect)
            (view->cmds (pad-node-child node) inner mx my))))

(define (render-margin node rect mx my)
  (let* ((t (margin-node-top    node))
         (r (margin-node-right  node))
         (b (margin-node-bottom node))
         (l (margin-node-left   node))
         (inner (make-rect (+ (rect-col rect) l)
                           (+ (rect-row rect) t)
                           (max 0 (- (rect-w rect) l r))
                           (max 0 (- (rect-h rect) t b)))))
    (view->cmds (margin-node-child node) inner mx my)))

(define (render-text-runs node rect mx my)
  (let loop ((runs (text-runs-node-runs node))
             (col  (rect-col rect))
             (acc  '())
             (rem  (rect-w rect)))
    (cond
     ((or (null? runs) (<= rem 0)) (reverse acc))
     (else
      (let* ((run (car runs))
             (s   (view-size run))
             (w   (min (car s) rem))
             (sub (make-rect col (rect-row rect) w 1))
             (cmds (view->cmds run sub mx my)))
        (loop (cdr runs) (+ col w) (append (reverse cmds) acc) (- rem w)))))))

(define (render-align node rect mx my)
  (let* ((child (align-node-child node))
         (mode (align-node-mode node))
         (target-w (or (align-node-width node) (rect-w rect)))
         (s (view-size child))
         (cw (min (car s) target-w))
         (slack (max 0 (- target-w cw)))
         (offset (case mode
                   ((center) (quotient slack 2))
                   ((right) slack)
                   (else 0)))
         (sub (make-rect (+ (rect-col rect) offset)
                         (rect-row rect)
                         cw
                         (rect-h rect))))
    (view->cmds child sub mx my)))

(define (render-width node rect mx my)
  (let* ((target-w (min (width-node-w node) (rect-w rect)))
         (child (width-node-child node))
         (align (width-node-align node))
         (s (view-size child))
         (cw (min (car s) target-w))
         (slack (max 0 (- target-w cw)))
         (offset (case align
                   ((center) (quotient slack 2))
                   ((right) slack)
                   (else 0)))
         (sub (make-rect (+ (rect-col rect) offset)
                         (rect-row rect)
                         cw
                         (rect-h rect))))
    (view->cmds child sub mx my)))

(define (render-height node rect mx my)
  (let* ((target-h (min (height-node-h node) (rect-h rect)))
         (child (height-node-child node))
         (valign (height-node-valign node))
         (s (view-size child))
         (ch (min (cdr s) target-h))
         (slack (max 0 (- target-h ch)))
         (offset (case valign
                   ((center) (quotient slack 2))
                   ((bottom) slack)
                   (else 0)))
         (sub (make-rect (rect-col rect)
                         (+ (rect-row rect) offset)
                         (rect-w rect)
                         ch)))
    (view->cmds child sub mx my)))
