;;; components/viewport.scm --- Scrollable viewport

(define-module (canary components viewport)
  #:use-module (canary text)
  #:use-module (srfi srfi-1)
  #:export (viewport))

(define (strip-cr str)
  (if (and (> (string-length str) 0)
           (char=? (string-ref str (- (string-length str) 1)) #\return))
      (substring str 0 (- (string-length str) 1))
      str))

(define* (viewport content #:key (width 40) (height 10) (offset-x 0) (offset-y 0))
  (let* ((lines (map strip-cr (string-split content #\newline)))
         (visible-lines (drop (take lines (min (+ offset-y height) (length lines)))
                             (min offset-y (length lines))))
         (cropped (map (lambda (line)
                        (let* ((vlen (visible-length line))
                               (start-pos (min offset-x vlen)))
                          (if (> vlen offset-x)
                              (let loop ((i 0) (vis-count 0) (result ""))
                                (if (or (>= i (string-length line))
                                       (>= vis-count (+ offset-x width)))
                                    result
                                    (let ((ch (string-ref line i)))
                                      (if (char=? ch #\escape)
                                          (let ((next-i (+ i 1)))
                                            (if (and (< next-i (string-length line))
                                                    (char=? (string-ref line next-i) #\[))
                                                (let skip-csi ((k (+ next-i 1)))
                                                  (if (>= k (string-length line))
                                                      (loop k vis-count result)
                                                      (let ((code (char->integer (string-ref line k))))
                                                        (if (and (>= code #x40) (<= code #x7E))
                                                            (loop (+ k 1) vis-count
                                                                  (string-append result (substring line i (+ k 1))))
                                                            (skip-csi (+ k 1))))))
                                                (loop next-i vis-count result)))
                                          (if (>= vis-count offset-x)
                                              (loop (+ i 1) (+ vis-count 1) (string-append result (string ch)))
                                              (loop (+ i 1) (+ vis-count 1) result))))))
                              "")))
                      visible-lines))
         (padded (map (lambda (line)
                       (let ((vlen (visible-length line)))
                         (if (< vlen width)
                             (string-append line (make-string (- width vlen) #\space))
                             line)))
                     cropped))
         (filled (if (< (length padded) height)
                     (append padded (make-list (- height (length padded))
                                               (make-string width #\space)))
                     padded)))
    (string-join filled nl)))
