(define-module (canary term ops)
  #:use-module (canary term types)
  #:export (term-cursor-up!
            term-cursor-down!
            term-cursor-left!
            term-cursor-right!
            term-cursor-horizontal-abs!
            term-cursor-vertical-abs!
            term-goto!
            term-save-cursor!
            term-restore-cursor!
            term-erase-in-line!
            term-erase-in-display!
            term-erase-char!
            term-insert-char!
            term-delete-char!
            term-insert-line!
            term-delete-line!
            term-scroll-up!
            term-scroll-down!
            term-horizontal-tab!
            term-horizontal-backtab!
            term-index!
            term-reverse-index!
            term-line-feed!
            term-carriage-return!
            term-set-scroll-region!
            term-enter-alt-screen!
            term-exit-alt-screen!
            term-current-bg-face))

(define (clamp-min v lo)
  (if (< v lo) lo v))

(define* (term-cursor-right! t #:optional (n 1))
  (let ((n (clamp-min n 1))
        (max-x (- (term-width t) 1)))
    (set-term-cursor-x! t (min (+ (term-cursor-x t) n) max-x))))

(define* (term-cursor-left! t #:optional (n 1))
  (let ((n (clamp-min n 1)))
    (set-term-cursor-x! t (max (- (term-cursor-x t) n) 0))))

(define* (term-cursor-down! t #:optional (n 1))
  (let ((n (clamp-min n 1))
        (max-y (- (term-height t) 1)))
    (set-term-cursor-y! t (min (+ (term-cursor-y t) n) max-y))))

(define* (term-cursor-up! t #:optional (n 1))
  (let ((n (clamp-min n 1)))
    (set-term-cursor-y! t (max (- (term-cursor-y t) n) 0))))

(define* (term-cursor-horizontal-abs! t #:optional (n 1))
  (set-term-cursor-x! t (min (max (- n 1) 0) (- (term-width t) 1))))

(define* (term-cursor-vertical-abs! t #:optional (n 1))
  (set-term-cursor-y! t (min (max (- n 1) 0) (- (term-height t) 1))))

(define* (term-goto! t #:optional (y 1) (x 1))
  (set-term-cursor-y! t (min (max (- (or y 1) 1) 0) (- (term-height t) 1)))
  (set-term-cursor-x! t (min (max (- (or x 1) 1) 0) (- (term-width t) 1))))

(define (term-save-cursor! t)
  (set-term-saved-cursor-x! t (term-cursor-x t))
  (set-term-saved-cursor-y! t (term-cursor-y t))
  (set-term-saved-attrs! t (copy-face-attrs (term-attrs t))))

(define (term-restore-cursor! t)
  (set-term-cursor-x! t (term-saved-cursor-x t))
  (set-term-cursor-y! t (term-saved-cursor-y t))
  (let ((saved (term-saved-attrs t)))
    (when saved
      (let ((cur (term-attrs t)))
        (set-face-fg! cur (face-fg saved))
        (set-face-bg! cur (face-bg saved))
        (set-face-bold! cur (face-bold? saved))
        (set-face-faint! cur (face-faint? saved))
        (set-face-italic! cur (face-italic? saved))
        (set-face-underline! cur (face-underline saved))
        (set-face-ul-color! cur (face-ul-color saved))
        (set-face-blink! cur (face-blink saved))
        (set-face-inverse! cur (face-inverse? saved))
        (set-face-conceal! cur (face-conceal? saved))
        (set-face-crossed! cur (face-crossed? saved))))))

(define (term-current-bg-face t)
  (and (face-bg (term-attrs t))
       (let ((cur (term-attrs t))
             (cached (term-last-write-face t)))
         (if (and cached (face-attrs-equal? cached cur))
             cached
             (let ((c (copy-face-attrs cur)))
               (set-term-last-write-face! t c)
               c)))))

(define (clear-cell! cell face)
  (set-cell-char! cell #\space)
  (set-cell-face! cell face))

(define* (term-erase-in-line! t #:optional (mode 0))
  (let* ((y (term-cursor-y t))
         (x (term-cursor-x t))
         (w (term-width t))
         (row (term-grid-row t y))
         (face (term-current-bg-face t)))
    (case mode
      ((0)
       (do ((i x (+ i 1)))
           ((= i w))
         (clear-cell! (vector-ref row i) face)))
      ((1)
       (do ((i 0 (+ i 1)))
           ((> i x))
         (clear-cell! (vector-ref row i) face)))
      ((2)
       (do ((i 0 (+ i 1)))
           ((= i w))
         (clear-cell! (vector-ref row i) face))))))

(define* (term-erase-in-display! t #:optional (mode 0))
  (let* ((y (term-cursor-y t))
         (h (term-height t))
         (face (term-current-bg-face t))
         (grid (term-grid t)))
    (case mode
      ((0)
       (term-erase-in-line! t 0)
       (do ((i (+ y 1) (+ i 1)))
           ((= i h))
         (clear-row! (vector-ref grid i) face)))
      ((1)
       (do ((i 0 (+ i 1)))
           ((= i y))
         (clear-row! (vector-ref grid i) face))
       (term-erase-in-line! t 1))
      ((2 3)
       (clear-grid! grid face)
       (when (= mode 3)
         (set-term-scrollback-size! t 0))))))

(define* (term-erase-char! t #:optional (n 1))
  (let* ((n (clamp-min n 1))
         (y (term-cursor-y t))
         (x (term-cursor-x t))
         (w (term-width t))
         (row (term-grid-row t y))
         (count (min n (- w x)))
         (face (term-current-bg-face t)))
    (do ((i x (+ i 1)))
        ((= i (+ x count)))
      (clear-cell! (vector-ref row i) face))))

(define* (term-insert-char! t #:optional (n 1))
  (let* ((n (clamp-min n 1))
         (y (term-cursor-y t))
         (x (term-cursor-x t))
         (w (term-width t))
         (row (term-grid-row t y))
         (count (min n (- w x)))
         (face (term-current-bg-face t)))
    (do ((i (- w 1) (- i 1)))
        ((< i (+ x count)))
      (let ((src (vector-ref row (- i count)))
            (dst (vector-ref row i)))
        (set-cell-char! dst (cell-char src))
        (set-cell-face! dst (cell-face src))))
    (do ((i x (+ i 1)))
        ((= i (+ x count)))
      (clear-cell! (vector-ref row i) face))))

(define* (term-delete-char! t #:optional (n 1))
  (let* ((n (clamp-min n 1))
         (y (term-cursor-y t))
         (x (term-cursor-x t))
         (w (term-width t))
         (row (term-grid-row t y))
         (count (min n (- w x)))
         (face (term-current-bg-face t)))
    (do ((i x (+ i 1)))
        ((= i (- w count)))
      (let ((src (vector-ref row (+ i count)))
            (dst (vector-ref row i)))
        (set-cell-char! dst (cell-char src))
        (set-cell-face! dst (cell-face src))))
    (do ((i (- w count) (+ i 1)))
        ((= i w))
      (clear-cell! (vector-ref row i) face))))

(define (push-scrollback! t row)
  (let ((sb (term-scrollback t))
        (max-sb (term-max-scrollback t)))
    (when (and sb (positive? max-sb))
      (when (>= (term-scrollback-size t) (vector-length sb))
        (let* ((cap (vector-length sb))
               (new-cap (min (* 2 (max cap 64)) max-sb))
               (new (make-vector new-cap #f)))
          (do ((i 0 (+ i 1)))
              ((= i (term-scrollback-size t)))
            (vector-set! new i (vector-ref sb i)))
          (set-term-scrollback! t new)
          (set! sb new)))
      (when (< (term-scrollback-size t) max-sb)
        (vector-set! sb (term-scrollback-size t) (copy-row row))
        (set-term-scrollback-size! t (+ (term-scrollback-size t) 1))))))

(define* (term-scroll-up! t #:optional (n 1))
  (let* ((n (clamp-min n 1))
         (top (term-scroll-top t))
         (bot (term-scroll-bottom t))
         (region-height (+ 1 (- bot top)))
         (count (min n region-height))
         (grid (term-grid t)))
    (when (positive? count)
      (when (and (zero? top) (not (term-in-alt? t)))
        (do ((i 0 (+ i 1)))
            ((= i count))
          (push-scrollback! t (vector-ref grid (+ top i)))))
      (let ((saved (make-vector count #f)))
        (do ((i 0 (+ i 1)))
            ((= i count))
          (vector-set! saved i (vector-ref grid (+ top i))))
        (do ((i top (+ i 1)))
            ((> i (- bot count)))
          (vector-set! grid i (vector-ref grid (+ i count))))
        (do ((i 0 (+ i 1)))
            ((= i count))
          (let ((row (vector-ref saved i)))
            (clear-row! row)
            (vector-set! grid (+ bot (- count) 1 i) row)))))))

(define* (term-scroll-down! t #:optional (n 1))
  (let* ((n (clamp-min n 1))
         (top (term-scroll-top t))
         (bot (term-scroll-bottom t))
         (region-height (+ 1 (- bot top)))
         (count (min n region-height))
         (grid (term-grid t)))
    (when (positive? count)
      (let ((saved (make-vector count #f)))
        (do ((i 0 (+ i 1)))
            ((= i count))
          (vector-set! saved i (vector-ref grid (+ bot (- count) 1 i))))
        (do ((i bot (- i 1)))
            ((< i (+ top count)))
          (vector-set! grid i (vector-ref grid (- i count))))
        (do ((i 0 (+ i 1)))
            ((= i count))
          (let ((row (vector-ref saved i)))
            (clear-row! row)
            (vector-set! grid (+ top i) row)))))))

(define* (term-insert-line! t #:optional (n 1))
  (let ((n (clamp-min n 1))
        (y (term-cursor-y t))
        (top (term-scroll-top t))
        (bot (term-scroll-bottom t)))
    (when (and (>= y top) (<= y bot))
      (let ((old-top top))
        (set-term-scroll-top! t y)
        (term-scroll-down! t (min n (+ 1 (- bot y))))
        (set-term-scroll-top! t old-top)))))

(define* (term-delete-line! t #:optional (n 1))
  (let ((n (clamp-min n 1))
        (y (term-cursor-y t))
        (top (term-scroll-top t))
        (bot (term-scroll-bottom t)))
    (when (and (>= y top) (<= y bot))
      (let ((old-top top))
        (set-term-scroll-top! t y)
        (term-scroll-up! t (min n (+ 1 (- bot y))))
        (set-term-scroll-top! t old-top)))))

(define* (term-horizontal-tab! t #:optional (n 1))
  (let* ((n (clamp-min n 1))
         (x (term-cursor-x t))
         (w (term-width t))
         (next-tab (+ x (- 8 (modulo x 8)))))
    (do ((i 1 (+ i 1)))
        ((= i n))
      (set! next-tab (+ next-tab 8)))
    (set-term-cursor-x! t (min next-tab (- w 1)))))

(define* (term-horizontal-backtab! t #:optional (n 1))
  (let* ((n (clamp-min n 1))
         (x (term-cursor-x t))
         (prev-tab (if (zero? (modulo x 8))
                       (- x 8)
                       (- x (modulo x 8)))))
    (do ((i 1 (+ i 1)))
        ((= i n))
      (set! prev-tab (- prev-tab 8)))
    (set-term-cursor-x! t (max prev-tab 0))))

(define (term-index! t)
  (let ((y (term-cursor-y t))
        (bot (term-scroll-bottom t)))
    (cond
     ((= y bot) (term-scroll-up! t 1))
     ((< y (- (term-height t) 1))
      (set-term-cursor-y! t (+ y 1))))))

(define (term-reverse-index! t)
  (let ((y (term-cursor-y t))
        (top (term-scroll-top t)))
    (cond
     ((= y top) (term-scroll-down! t 1))
     ((> y 0)
      (set-term-cursor-y! t (- y 1))))))

(define (term-line-feed! t)
  (let* ((y (term-cursor-y t))
         (bot (term-scroll-bottom t)))
    (set-term-cursor-x! t 0)
    (cond
     ((= y bot) (term-scroll-up! t 1))
     ((< y (- (term-height t) 1))
      (set-term-cursor-y! t (+ y 1))))))

(define (term-carriage-return! t)
  (set-term-cursor-x! t 0))

(define* (term-set-scroll-region! t #:optional top bottom)
  (let ((tv (or top 1))
        (bv (or bottom (term-height t))))
    (when (and (< 0 tv) (< tv bv) (<= bv (term-height t)))
      (set-term-scroll-top! t (- tv 1))
      (set-term-scroll-bottom! t (- bv 1))
      (term-goto! t 1 1))))

(define (term-enter-alt-screen! t)
  (unless (term-in-alt? t)
    (set-term-main-grid! t (term-grid t))
    (set-term-grid! t (make-grid (term-width t) (term-height t)))
    (set-term-in-alt! t #t)
    (term-goto! t 1 1)))

(define (term-exit-alt-screen! t)
  (when (term-in-alt? t)
    (set-term-grid! t (term-main-grid t))
    (set-term-main-grid! t #f)
    (set-term-in-alt! t #f)))
