(define-module (canary term parser)
  #:use-module (canary term types)
  #:use-module (canary term ops)
  #:use-module (canary term sgr)
  #:use-module (canary term write)
  #:export (term-process-output!))

(define (control-byte? ch)
  (let ((code (char->integer ch)))
    (or (<= code 31)
        (= code 127))))

(define (term-process-output! t str)
  (let ((len (string-length str)))
    (let loop ((idx 0))
      (when (< idx len)
        (let ((state (term-parser-state t)))
          (cond
           ((not state)
            (set! idx (handle-ground t str idx len)))
           ((eq? state 'esc)
            (set! idx (handle-esc t str idx len)))
           ((and (pair? state) (eq? (car state) 'charset))
            (set! idx (handle-charset t str idx len (cadr state))))
           ((eq? state 'csi-fmt)
            (set! idx (handle-csi-fmt t str idx len)))
           ((eq? state 'csi-params)
            (set! idx (handle-csi-params t str idx len)))
           ((eq? state 'csi-fn)
            (set! idx (handle-csi-fn t str idx len)))
           ((eq? state 'osc)
            (set! idx (handle-osc t str idx len)))
           ((eq? state 'dcs)
            (set! idx (handle-dcs t str idx len)))
           (else
            (set-term-parser-state! t #f)
            (set! idx (+ idx 1))))
          (loop idx))))))

(define (handle-ground t str idx len)
  (let ((span-start idx)
        (i idx))
    (let scan ()
      (when (and (< i len)
                 (let ((ch (string-ref str i)))
                   (and (not (control-byte? ch))
                        (not (char=? ch #\esc)))))
        (set! i (+ i 1))
        (scan)))
    (when (> i span-start)
      (term-write! t str span-start i))
    (cond
     ((>= i len) i)
     (else
      (let ((ch (string-ref str i))
            (next-idx (+ i 1)))
        (cond
         ((char=? ch #\alarm)
          (when (term-bell-fn t) ((term-bell-fn t) t))
          next-idx)
         ((char=? ch #\backspace)
          (term-cursor-left! t 1)
          next-idx)
         ((char=? ch #\tab)
          (term-horizontal-tab! t 1)
          next-idx)
         ((char=? ch #\newline)
          (term-line-feed! t)
          next-idx)
         ((or (char=? ch #\vtab) (char=? ch #\page))
          (term-index! t)
          next-idx)
         ((char=? ch #\return)
          (unless (and (< next-idx len)
                       (char=? (string-ref str next-idx) #\newline))
            (term-carriage-return! t))
          next-idx)
         ((char=? ch (integer->char #x0E))
          (set-term-active-charset! t 'g1)
          next-idx)
         ((char=? ch (integer->char #x0F))
          (set-term-active-charset! t 'g0)
          next-idx)
         ((char=? ch #\esc)
          (set-term-parser-state! t 'esc)
          next-idx)
         (else next-idx)))))))

(define (handle-esc t str idx len)
  (let ((ch (string-ref str idx))
        (next-idx (+ idx 1)))
    (set-term-parser-state! t #f)
    (cond
     ((char=? ch #\() (set-term-parser-state! t '(charset g0)))
     ((char=? ch #\)) (set-term-parser-state! t '(charset g1)))
     ((char=? ch #\*) (set-term-parser-state! t '(charset g2)))
     ((char=? ch #\+) (set-term-parser-state! t '(charset g3)))
     ((char=? ch #\7) (term-save-cursor! t))
     ((char=? ch #\8) (term-restore-cursor! t))
     ((char=? ch #\D) (term-index! t))
     ((char=? ch #\E)
      (term-carriage-return! t)
      (term-line-feed! t))
     ((char=? ch #\M) (term-reverse-index! t))
     ((char=? ch #\[)
      (set-term-parser-state! t 'csi-fmt)
      (set-term-csi-format! t #f)
      (set-term-csi-params! t (list #f)))
     ((char=? ch #\])
      (set-term-parser-state! t 'osc)
      (set-term-osc-buf! t ""))
     ((char=? ch #\P)
      (set-term-parser-state! t 'dcs))
     ((char=? ch #\c) (term-reset! t))
     ((char=? ch #\n) (set-term-active-charset! t 'g2))
     ((char=? ch #\o) (set-term-active-charset! t 'g3))
     (else #f))
    next-idx))

(define (handle-charset t str idx len slot)
  (let ((ch (string-ref str idx)))
    (set-term-parser-state! t #f)
    (let ((charset (case ch
                     ((#\0) 'dec-line-drawing)
                     ((#\B) 'us-ascii)
                     (else 'us-ascii))))
      (case slot
        ((g0) (set-term-g0! t charset))
        ((g1) (set-term-g1! t charset))
        ((g2) (set-term-g2! t charset))
        ((g3) (set-term-g3! t charset))))
    (+ idx 1)))

(define (handle-csi-fmt t str idx len)
  (let ((ch (string-ref str idx)))
    (cond
     ((char=? ch #\?)
      (set-term-csi-format! t #\?)
      (set-term-parser-state! t 'csi-params)
      (+ idx 1))
     ((char=? ch #\>)
      (set-term-csi-format! t #\>)
      (set-term-parser-state! t 'csi-params)
      (+ idx 1))
     ((char=? ch #\=)
      (set-term-csi-format! t #\=)
      (set-term-parser-state! t 'csi-params)
      (+ idx 1))
     (else
      (set-term-csi-format! t #f)
      (set-term-parser-state! t 'csi-params)
      idx))))

(define (handle-csi-params t str idx len)
  (let ((ch (string-ref str idx)))
    (cond
     ((and (char>=? ch #\0) (char<=? ch #\9))
      (let* ((digit (- (char->integer ch) (char->integer #\0)))
             (params (term-csi-params t))
             (head (car params))
             (rest (cdr params))
             (new-head (+ (* (or head 0) 10) digit)))
        (set-term-csi-params! t (cons new-head rest))
        (+ idx 1)))
     ((char=? ch #\;)
      (set-term-csi-params! t (cons #f (term-csi-params t)))
      (+ idx 1))
     ((char=? ch #\:)
      ;; Promote head into a sublist (kept ordered).
      (let* ((params (term-csi-params t))
             (head (car params))
             (rest (cdr params)))
        (cond
         ((pair? head)
          ;; Already a sublist: append a new slot.
          (set-term-csi-params! t (cons (append head (list #f)) rest)))
         (else
          (set-term-csi-params! t (cons (list head #f) rest))))
        (+ idx 1)))
     (else
      (set-term-parser-state! t 'csi-fn)
      idx))))

(define (handle-csi-fn t str idx len)
  (let ((ch (string-ref str idx)))
    (cond
     ((and (char>=? ch #\@) (char<=? ch #\~))
      (set-term-parser-state! t #f)
      (let ((params (reverse (term-csi-params t)))
            (fmt (term-csi-format t)))
        (dispatch-csi t ch fmt params))
      (+ idx 1))
     (else (+ idx 1)))))

(define (handle-osc t str idx len)
  (let scan ((i idx))
    (cond
     ((= i len)
      (set-term-osc-buf!
       t (string-append (term-osc-buf t) (substring str idx i)))
      i)
     ((or (char=? (string-ref str i) #\alarm)
          (char=? (string-ref str i) #\\))
      (let ((chunk (substring str idx i)))
        (set-term-osc-buf! t (string-append (term-osc-buf t) chunk))
        (cond
         ((and (char=? (string-ref str i) #\\)
               (positive? (string-length (term-osc-buf t)))
               (char=? (string-ref (term-osc-buf t)
                                   (- (string-length (term-osc-buf t)) 1))
                       #\esc))
          ;; ST = ESC \ ; strip trailing ESC
          (set-term-osc-buf!
           t (substring (term-osc-buf t) 0
                        (- (string-length (term-osc-buf t)) 1))))
         (else #t))
        (dispatch-osc t (term-osc-buf t))
        (set-term-parser-state! t #f)
        (set-term-osc-buf! t "")
        (+ i 1)))
     (else (scan (+ i 1))))))

(define (handle-dcs t str idx len)
  ;; Skip until ESC \\ ST.
  (let scan ((i idx))
    (cond
     ((>= i len) len)
     ((and (char=? (string-ref str i) #\esc)
           (< (+ i 1) len)
           (char=? (string-ref str (+ i 1)) #\\))
      (set-term-parser-state! t #f)
      (+ i 2))
     (else (scan (+ i 1))))))

(define (dispatch-csi t ch fmt params)
  (let ((p1 (and (pair? params) (car params)))
        (p2 (and (pair? params) (pair? (cdr params)) (cadr params))))
    (define (or1 v) (or v 1))
    (define (or0 v) (or v 0))
    (cond
     ((char=? ch #\@) (term-insert-char! t (or1 p1)))
     ((or (char=? ch #\A) (char=? ch #\k)) (term-cursor-up! t (or1 p1)))
     ((or (char=? ch #\B) (char=? ch #\e)) (term-cursor-down! t (or1 p1)))
     ((or (char=? ch #\C) (char=? ch #\a)) (term-cursor-right! t (or1 p1)))
     ((or (char=? ch #\D) (char=? ch #\j)) (term-cursor-left! t (or1 p1)))
     ((char=? ch #\E)
      (term-cursor-down! t (or1 p1))
      (term-carriage-return! t))
     ((char=? ch #\F)
      (term-cursor-up! t (or1 p1))
      (term-carriage-return! t))
     ((or (char=? ch #\G) (char=? ch #\`))
      (term-cursor-horizontal-abs! t (or1 p1)))
     ((or (char=? ch #\H) (char=? ch #\f))
      (term-goto! t (or1 p1) (or1 p2)))
     ((char=? ch #\I) (term-horizontal-tab! t (or1 p1)))
     ((char=? ch #\J) (term-erase-in-display! t (or0 p1)))
     ((char=? ch #\K) (term-erase-in-line! t (or0 p1)))
     ((char=? ch #\L) (term-insert-line! t (or1 p1)))
     ((char=? ch #\M) (term-delete-line! t (or1 p1)))
     ((char=? ch #\P) (term-delete-char! t (or1 p1)))
     ((char=? ch #\S)
      (unless (eqv? fmt #\?)
        (term-scroll-up! t (or1 p1))))
     ((char=? ch #\T) (term-scroll-down! t (or1 p1)))
     ((char=? ch #\X) (term-erase-char! t (or1 p1)))
     ((char=? ch #\Z) (term-horizontal-backtab! t (or1 p1)))
     ((char=? ch #\b)
      (let ((n (or1 p1))
            (last (term-last-char t)))
        (when (and (char? last)
                   (let ((c (char->integer last)))
                     (and (>= c 32) (not (= c 127)))))
          (term-write! t (make-string n last)))))
     ((char=? ch #\c) (dispatch-device-attrs t (or0 p1) fmt))
     ((char=? ch #\d) (term-cursor-vertical-abs! t (or1 p1)))
     ((char=? ch #\h) (dispatch-set-modes t params fmt #t))
     ((char=? ch #\l) (dispatch-set-modes t params fmt #f))
     ((char=? ch #\m)
      (unless fmt (process-sgr! t params)))
     ((char=? ch #\n) (dispatch-device-status t (or0 p1)))
     ((char=? ch #\q)
      (when (and (>= (length params) 1) (not fmt))
        (dispatch-cursor-style t (or0 p1))))
     ((char=? ch #\r) (term-set-scroll-region! t p1 p2))
     ((char=? ch #\s) (when (not fmt) (term-save-cursor! t)))
     ((char=? ch #\u) (when (not fmt) (term-restore-cursor! t)))
     (else #f))))

(define (dispatch-device-attrs t n fmt)
  (when (term-input-fn t)
    (cond
     ((not fmt)
      (when (zero? n)
        ((term-input-fn t) t (string #\esc #\[ #\? #\1 #\2 #\; #\4 #\c))))
     ((eqv? fmt #\>)
      (when (zero? n)
        ((term-input-fn t) t (string #\esc #\[ #\> #\0 #\; #\0 #\; #\0 #\c)))))))

(define (dispatch-device-status t n)
  (when (term-input-fn t)
    (case n
      ((5) ((term-input-fn t) t (string #\esc #\[ #\0 #\n)))
      ((6) ((term-input-fn t) t
             (string-append (string #\esc) "["
                            (number->string (+ 1 (term-cursor-y t)))
                            ";"
                            (number->string (+ 1 (term-cursor-x t)))
                            "R"))))))

(define *cursor-styles*
  #(blinking-block blinking-block block
    blinking-underline underline
    blinking-bar bar))

(define (dispatch-cursor-style t style)
  (when (and (>= style 0) (<= style 6))
    (set-term-cursor-style! t (vector-ref *cursor-styles* style))))

(define (dispatch-set-modes t params fmt set?)
  (for-each
   (lambda (p)
     (when p
       (cond
        ((not fmt)
         (case p
           ((4) (set-term-insert! t set?))))
        ((eqv? fmt #\?)
         (case p
           ((1) (set-term-keypad! t set?))
           ((7) (set-term-auto-margin! t set?))
           ((12)
            (cond
             (set?
              (case (term-cursor-style t)
                ((block) (set-term-cursor-style! t 'blinking-block))
                ((underline) (set-term-cursor-style! t 'blinking-underline))
                ((bar) (set-term-cursor-style! t 'blinking-bar))))
             (else
              (case (term-cursor-style t)
                ((blinking-block) (set-term-cursor-style! t 'block))
                ((blinking-underline) (set-term-cursor-style! t 'underline))
                ((blinking-bar) (set-term-cursor-style! t 'bar))))))
           ((25) (set-term-cursor-visible! t set?))
           ((1047)
            (if set? (term-enter-alt-screen! t)
                     (term-exit-alt-screen! t)))
           ((1048)
            (if set? (term-save-cursor! t)
                     (term-restore-cursor! t)))
           ((1049)
            (cond
             (set? (term-save-cursor! t) (term-enter-alt-screen! t))
             (else (term-exit-alt-screen! t) (term-restore-cursor! t))))
           ((2004) (set-term-bracketed-paste! t set?)))))))
   params))

(define (dispatch-osc t s)
  (let ((semi (string-index s #\;)))
    (when semi
      (let ((code (substring s 0 semi))
            (data (substring s (+ semi 1))))
        (cond
         ((or (string=? code "0") (string=? code "2"))
          (set-term-title! t data)
          (when (term-title-fn t) ((term-title-fn t) t data)))
         ((string=? code "7")
          (set-term-cwd! t data)
          (when (term-cwd-fn t) ((term-cwd-fn t) t data)))
         ((string=? code "10")
          (when (and (string=? data "?") (term-input-fn t))
            ((term-input-fn t) t
             (string-append (string #\esc) "]10;rgb:d8d8/d8d8/d8d8"
                            (string #\esc) "\\"))))
         ((string=? code "11")
          (when (and (string=? data "?") (term-input-fn t))
            ((term-input-fn t) t
             (string-append (string #\esc) "]11;rgb:1818/1818/1818"
                            (string #\esc) "\\")))))))))

(define (string-index s ch)
  (let ((len (string-length s)))
    (let loop ((i 0))
      (cond
       ((= i len) #f)
       ((char=? (string-ref s i) ch) i)
       (else (loop (+ i 1)))))))
