(define-module (canary term sgr)
  #:use-module (canary term types)
  #:export (process-sgr!))

(define (process-sgr! t params)
  (let* ((attrs (term-attrs t))
         (vec (list->vector params))
         (len (vector-length vec))
         (i 0))
    (define (peek)
      (and (< i len) (vector-ref vec i)))
    (define (next)
      (if (< i len)
          (let ((v (vector-ref vec i)))
            (set! i (+ i 1))
            v)
          #f))
    (cond
     ((zero? len)
      (reset-face-attrs! attrs))
     (else
      (let loop ()
        (when (< i len)
          (let ((code (or (next) 0)))
            (cond
             ((eq? code 0) (reset-face-attrs! attrs))
             ((eq? code 1) (set-face-bold! attrs #t)
                           (set-face-faint! attrs #f))
             ((eq? code 2) (set-face-faint! attrs #t)
                           (set-face-bold! attrs #f))
             ((eq? code 3) (set-face-italic! attrs #t))
             ((eq? code 4)
              (let ((sub (peek)))
                (cond
                 ((and (pair? sub) (pair? (cdr sub)))
                  (next)
                  (let ((s (cadr sub)))
                    (case s
                      ((0) (set-face-underline! attrs #f))
                      ((1) (set-face-underline! attrs 'single))
                      ((2) (set-face-underline! attrs 'double))
                      ((3) (set-face-underline! attrs 'curly))
                      ((4) (set-face-underline! attrs 'dotted))
                      ((5) (set-face-underline! attrs 'dashed))
                      (else (set-face-underline! attrs 'single)))))
                 (else
                  (set-face-underline! attrs 'single)))))
             ((eq? code 5) (set-face-blink! attrs 'slow))
             ((eq? code 6) (set-face-blink! attrs 'fast))
             ((eq? code 7) (set-face-inverse! attrs #t))
             ((eq? code 8) (set-face-conceal! attrs #t))
             ((eq? code 9) (set-face-crossed! attrs #t))
             ((eq? code 21) (set-face-underline! attrs 'double))
             ((eq? code 22) (set-face-bold! attrs #f)
                            (set-face-faint! attrs #f))
             ((eq? code 23) (set-face-italic! attrs #f))
             ((eq? code 24) (set-face-underline! attrs #f))
             ((eq? code 25) (set-face-blink! attrs #f))
             ((eq? code 27) (set-face-inverse! attrs #f))
             ((eq? code 28) (set-face-conceal! attrs #f))
             ((eq? code 29) (set-face-crossed! attrs #f))
             ((eq? code 39) (set-face-fg! attrs #f))
             ((eq? code 49) (set-face-bg! attrs #f))
             ((eq? code 59) (set-face-ul-color! attrs #f))
             ((and (>= code 30) (<= code 37))
              (set-face-fg! attrs (- code 30)))
             ((and (>= code 40) (<= code 47))
              (set-face-bg! attrs (- code 40)))
             ((and (>= code 90) (<= code 97))
              (set-face-fg! attrs (+ 8 (- code 90))))
             ((and (>= code 100) (<= code 107))
              (set-face-bg! attrs (+ 8 (- code 100))))
             ((eq? code 38) (consume-extended-color! attrs 'fg next))
             ((eq? code 48) (consume-extended-color! attrs 'bg next))
             ((eq? code 58) (consume-extended-color! attrs 'ul next))
             (else #f)))
          (loop)))))))

(define (consume-extended-color! attrs slot next)
  (let ((mode (next)))
    (cond
     ((eq? mode 5)
      (let ((c (next)))
        (when (and c (>= c 0) (<= c 255))
          (case slot
            ((fg) (set-face-fg! attrs c))
            ((bg) (set-face-bg! attrs c))
            ((ul) (set-face-ul-color! attrs c))))))
     ((eq? mode 2)
      (let ((r (next)) (g (next)) (b (next)))
        (when (and r g b
                   (>= r 0) (<= r 255)
                   (>= g 0) (<= g 255)
                   (>= b 0) (<= b 255))
          (let ((rgb (list r g b)))
            (case slot
              ((fg) (set-face-fg! attrs rgb))
              ((bg) (set-face-bg! attrs rgb))
              ((ul) (set-face-ul-color! attrs rgb))))))))))
