(define-module (canary term write)
  #:use-module (canary term types)
  #:use-module (canary term ops)
  #:export (term-write!
            char-display-width))

(define *dec-line-drawing*
  (let ((h (make-hash-table)))
    (for-each (lambda (pair)
                (hash-set! h (car pair) (cdr pair)))
              '((#\+ . #\→) (#\, . #\←) (#\- . #\↑) (#\. . #\↓)
                (#\0 . #\█) (#\` . #\◆) (#\a . #\▒) (#\f . #\°)
                (#\g . #\±) (#\h . #\░) (#\i . #\#)
                (#\j . #\┘) (#\k . #\┐) (#\l . #\┌) (#\m . #\└)
                (#\n . #\┼) (#\o . #\⎺) (#\p . #\⎻) (#\q . #\─)
                (#\r . #\⎼) (#\s . #\⎽) (#\t . #\├) (#\u . #\┤)
                (#\v . #\┴) (#\w . #\┬) (#\x . #\│) (#\y . #\≤)
                (#\z . #\≥) (#\{ . #\π) (#\| . #\≠) (#\} . #\£)
                (#\~ . #\•)))
    h))

(define (translate-charset ch charset)
  (case charset
    ((dec-line-drawing)
     (or (hash-ref *dec-line-drawing* ch) ch))
    (else ch)))

(define (current-charset-mapping t)
  (case (term-active-charset t)
    ((g0) (term-g0 t))
    ((g1) (term-g1 t))
    ((g2) (term-g2 t))
    ((g3) (term-g3 t))
    (else 'us-ascii)))

(define (char-display-width ch)
  (let ((code (char->integer ch)))
    (cond
     ((< code 32) 0)
     ((= code #x7F) 0)
     ((or (and (<= #x0300 code) (<= code #x036F))
          (and (<= #x0483 code) (<= code #x0489))
          (and (<= #x0591 code) (<= code #x05C7))
          (and (<= #x064B code) (<= code #x065F))
          (and (<= #x200B code) (<= code #x200F))
          (and (<= #x20D0 code) (<= code #x20FF))
          (and (<= #xFE20 code) (<= code #xFE2F)))
      0)
     ((or (and (<= #x1100 code) (<= code #x115F))
          (and (<= #x2E80 code) (<= code #x2FFF))
          (and (<= #x3000 code) (<= code #x9FFF))
          (and (<= #xAC00 code) (<= code #xD7A3))
          (and (<= #xF900 code) (<= code #xFAFF))
          (and (<= #xFF01 code) (<= code #xFF60))
          (and (<= #x1F300 code) (<= code #x1F9FF)))
      2)
     (else 1))))

(define (current-write-face t)
  (let ((cur (term-attrs t))
        (cached (term-last-write-face t)))
    (if (and cached (face-attrs-equal? cached cur))
        cached
        (let ((c (copy-face-attrs cur)))
          (set-term-last-write-face! t c)
          c))))

(define* (term-write! t str #:optional (start 0) (end #f))
  (let* ((end (or end (string-length str)))
         (w (term-width t))
         (charset (current-charset-mapping t))
         (face (current-write-face t)))
    (let loop ((idx start))
      (when (< idx end)
        (let* ((raw (string-ref str idx))
               (ch (translate-charset raw charset))
               (cw (char-display-width ch)))
          (unless (zero? cw)
            (set-term-last-char! t ch)
            (when (term-insert? t)
              (term-insert-char! t cw))
            (when (>= (term-cursor-x t) w)
              (cond
               ((term-auto-margin? t)
                (set-term-cursor-x! t 0)
                (cond
                 ((= (term-cursor-y t) (term-scroll-bottom t))
                  (term-scroll-up! t 1))
                 (else
                  (set-term-cursor-y! t (+ (term-cursor-y t) 1)))))
               (else
                (set-term-cursor-x! t (- w 1)))))
            (let* ((x (term-cursor-x t))
                   (y (term-cursor-y t))
                   (row (term-grid-row t y)))
              (cond
               ((and (= cw 2) (>= (+ x 1) w))
                (let ((cell (vector-ref row x)))
                  (set-cell-char! cell #\space)
                  (set-cell-face! cell face))
                (set-term-cursor-x! t 0)
                (cond
                 ((= y (term-scroll-bottom t))
                  (term-scroll-up! t 1))
                 (else
                  (set-term-cursor-y! t (+ y 1))))
                (let* ((x2 (term-cursor-x t))
                       (y2 (term-cursor-y t))
                       (row2 (term-grid-row t y2))
                       (c (vector-ref row2 x2)))
                  (set-cell-char! c ch)
                  (set-cell-face! c face)
                  (when (and (= cw 2) (< (+ x2 1) w))
                    (let ((c2 (vector-ref row2 (+ x2 1))))
                      (set-cell-char! c2 #\space)
                      (set-cell-face! c2 face)))
                  (set-term-cursor-x! t (+ x2 cw))))
               (else
                (let ((cell (vector-ref row x)))
                  (set-cell-char! cell ch)
                  (set-cell-face! cell face))
                (when (and (= cw 2) (< (+ x 1) w))
                  (let ((c2 (vector-ref row (+ x 1))))
                    (set-cell-char! c2 #\space)
                    (set-cell-face! c2 face)))
                (set-term-cursor-x! t (+ x cw))))))
          (loop (+ idx 1)))))))
